[package]
name = "tftprust"
version = "0.1.0"
authors = ["raptorswing"]
edition = "2018"

[dependencies]
anyhow = "1.0.57"
async-std = "1.11.0"
futures = { version = "0.3", default-features = true, features = ["thread-pool"] }
thiserror = "1.0.31"