[package]
name = "tftprust"
version = "0.1.0"
authors = ["raptorswing"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ascii = "0.9.2"
futures = "0.1.28"
tokio = "0.1.22"